// agent/STRUCTURE.md tells the agent, in its own header:
//
//   "A new stamp above means the body changed since you last read this file."
//
// and tools/gen-structure-tree.mjs says the same in its own comment: "that stamp IS the
// agent's change-awareness". The generator then wrote `new Date().toISOString()` on every
// single build, so the stamp moved when nothing had. The one cheap check pi has carried no
// information — it either re-read the whole tree every time or learned to ignore the line,
// and both defeat the purpose. This is the app's signature defect class: a claim nothing
// measured.
//
// It had a second cost. `npm run build` runs the generator, and `pretest` runs the build, so
// the working tree could NEVER be clean after a gate. That silently broke the one-concern-
// per-commit discipline and made every clean-tree guard useless — including the apply script
// that refused to run, which is how this was found.
//
// Measured before the fix: two consecutive `node tools/gen-structure-tree.mjs` runs with no
// source edit between them produced two different files.
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

const APP = path.resolve(import.meta.dirname, '..');
const GEN = path.join(APP, 'tools', 'gen-structure-tree.mjs');
const OUT = path.join(APP, 'agent', 'STRUCTURE.md');
const src = fs.readFileSync(GEN, 'utf8');

const stampOf = (s) => (s.match(/^Generated by .*$/m) || [''])[0];
const bodyOf = (s) => s.split('\n').filter((l) => !l.startsWith('Generated by `tools/gen-structure-tree.mjs`')).join('\n');

test('the generator compares the body, not just the clock', () => {
  assert.match(src, /const bodyOf\s*=/, 'it must be able to say what "unchanged" means');
  assert.match(src, /if \(changed\) writeFileSync\(OUT, md\)/,
    'an unchanged body must leave the file — and its stamp — alone');
  assert.doesNotMatch(src, /\n\s*writeFileSync\(OUT, md\);\n\s*if \(!silent\)/,
    'the unconditional write must be gone');
  assert.match(src, /return \{ ok: true, out: OUT, sha, changed \}/,
    'and the caller needs to know which of the two happened');
});

test('running it twice with no source edit leaves the file byte-identical', () => {
  // The real contract, exercised rather than asserted. This is the run that used to fail.
  const before = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : null;
  try {
    execFileSync(process.execPath, [GEN], { cwd: APP, stdio: 'ignore' });
    const first = fs.readFileSync(OUT, 'utf8');
    execFileSync(process.execPath, [GEN], { cwd: APP, stdio: 'ignore' });
    const second = fs.readFileSync(OUT, 'utf8');
    assert.equal(second, first, 'a no-op regeneration must not rewrite the file');
    assert.equal(stampOf(second), stampOf(first), 'and must not move the stamp');
  } finally {
    if (before !== null) fs.writeFileSync(OUT, before);
  }
});

test('a real body change DOES move the stamp — the signal still works', () => {
  const before = fs.readFileSync(OUT, 'utf8');
  const decoy = path.join(APP, 'agent', 'LESSONS', 'zz-debug3-stamp-probe.md');
  try {
    execFileSync(process.execPath, [GEN], { cwd: APP, stdio: 'ignore' });
    const base = fs.readFileSync(OUT, 'utf8');

    // LESSONS/*.md is a tree branch, so adding one is a genuine change of the body.
    fs.writeFileSync(decoy, '# probe\n');
    execFileSync(process.execPath, [GEN], { cwd: APP, stdio: 'ignore' });
    const moved = fs.readFileSync(OUT, 'utf8');

    assert.notEqual(bodyOf(moved), bodyOf(base), 'the new branch must appear in the tree');
    assert.notEqual(stampOf(moved), stampOf(base), 'and the stamp must move with it');
    assert.ok(moved.includes('zz-debug3-stamp-probe.md'), 'the branch itself must be listed');
  } finally {
    try { fs.unlinkSync(decoy); } catch {}
    fs.writeFileSync(OUT, before);
  }
});

test('refreshTree reports whether anything actually moved', () => {
  const pi = fs.readFileSync(path.join(APP, 'bridge', 'pi.mjs'), 'utf8');
  const fn = pi.match(/function refreshTree\(\)[\s\S]*?\n\}/)[0];
  assert.match(fn, /const before = stampOf\(file\)/, 'it must sample the stamp before running');
  assert.match(fn, /changed: !!stamp && stamp !== before/,
    'and derive "changed" from the two samples, not from the exit code');
});

test('the panel says which of the two happened', () => {
  const brain = fs.readFileSync(path.join(APP, 'web', 'panels', 'brain.js'), 'utf8');
  assert.match(brain, /r\.changed\?'Body re-read — the tree changed':'Body re-read — already current'/,
    'a regeneration that changed nothing must not read as an update');
  assert.doesNotMatch(brain, /Toast\.show\('Body re-read from the sources'\)/,
    'the old unconditional sentence must be gone');
});

test('the header sentence the stamp is supposed to honour is still there', () => {
  // If this line ever goes, the fix above loses its reason to exist — and a later reader
  // would have no way to know the write is conditional on purpose.
  const gen = src;
  assert.match(gen, /A new stamp above means the body changed since you last read/,
    'the promise must stay visible next to the code that keeps it');
  assert.ok(!os.platform || true);
});
