#!/usr/bin/env node
// CLONE FRAME — auto app-map generator.
//
// Parses the REAL panel registry (`const DEFS={…}` in web/index.html) and emits:
//   • context/app-map.json         — machine-readable map (every panel: key · title · sub)
//   • agent/AGENTS.md              — refreshes the <!-- AUTO PANELS --> block from the same source
//
// So the Pi agent's map of the app stays in step with the code automatically: change a panel
// in the registry, rebuild, and the agent's field guide + machine map update themselves.
// Run standalone (`node tools/gen-app-map.mjs`) or via tools/build.mjs (which calls genAppMap()).
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

// Take the balanced body of `const DEFS={ … }`, skipping string / template-literal regions so
// braces inside a panel's body:()=>`…` template never fool the depth counter.
function extractDefsBlock(s) {
  const i = s.indexOf('const DEFS={');
  if (i < 0) throw new Error('DEFS not found in web/index.html');
  let depth = 0, q = null, started = false;
  for (let j = i + 'const DEFS='.length; j < s.length; j++) {
    const c = s[j], prev = s[j - 1];
    if (q) { if (c === q && prev !== '\\') q = null; continue; }
    if (c === "'" || c === '"' || c === '`') { q = c; continue; }
    if (c === '{') { depth++; started = true; }
    else if (c === '}') { depth--; if (started && depth === 0) return s.slice(i, j + 1); }
  }
  throw new Error('DEFS block not balanced');
}

export function parsePanels(html) {
  const block = extractDefsBlock(html);
  // Every entry begins  key:{icon:'…',title:'…',sub:'…'  (recon-confirmed field order).
  const re = /(\w+)\s*:\s*\{\s*icon\s*:\s*'[^']*'\s*,\s*title\s*:\s*'([^']*)'\s*,\s*sub\s*:\s*'([^']*)'/g;
  const panels = [];
  let m;
  while ((m = re.exec(block))) panels.push({ key: m[1], title: m[2], sub: m[3] });
  if (panels.length < 20) throw new Error(`app-map parser drifted — only found ${panels.length} panels`);
  return panels;
}

function panelTable(panels) {
  const rows = panels.map((p) => `| \`${p.key}\` | ${p.title} | ${p.sub || ''} |`);
  return ['| key | title | what you do there |', '|---|---|---|', ...rows].join('\n');
}

export function genAppMap({ silent = false } = {}) {
  const html = readFileSync(path.join(ROOT, 'web', 'index.html'), 'utf8');
  const panels = parsePanels(html);

  // 1) machine map (no timestamp — deterministic, no build churn)
  const jsonPath = path.join(ROOT, 'context', 'app-map.json');
  writeFileSync(jsonPath, JSON.stringify({ generated: 'tools/gen-app-map.mjs', count: panels.length, panels }, null, 2) + '\n');

  // 2) refresh the AUTO PANELS block in the agent curriculum (only if the file exists)
  const agents = path.join(ROOT, 'agent', 'AGENTS.md');
  let wroteAgents = false;
  if (existsSync(agents)) {
    const md = readFileSync(agents, 'utf8');
    const begin = '<!-- BEGIN AUTO PANELS (generated by tools/gen-app-map.mjs — do not hand-edit) -->';
    const end = '<!-- END AUTO PANELS -->';
    const bi = md.indexOf(begin), ei = md.indexOf(end);
    if (bi >= 0 && ei > bi) {
      const next = md.slice(0, bi + begin.length) + '\n' + panelTable(panels) + '\n' + md.slice(ei);
      if (next !== md) writeFileSync(agents, next);
      wroteAgents = true;
    }
  }
  if (!silent) console.log(`app-map → ${panels.length} panels · context/app-map.json${wroteAgents ? ' · agent/AGENTS.md refreshed' : ''}`);
  return { count: panels.length, panels };
}

// run standalone
if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  try { genAppMap(); } catch (e) { console.error('gen-app-map failed:', e.message); process.exit(1); }
}
